# Generated by Django 4.2.2 on 2024-08-18 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0002_alter_employee_contact_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='name',
        ),
    ]
