# Generated by Django 4.2.2 on 2024-08-19 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0004_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='contact_number',
        ),
    ]
