# Generated by Django 5.1 on 2024-08-23 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student_management_app", "0007_staff_delete_staffs"),
    ]

    operations = [
        migrations.CreateModel(
            name="StaffLeave",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("from_date", models.CharField(max_length=50)),
                ("to_date", models.CharField(max_length=50)),
                ("messages", models.TextField()),
                ("status", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "staff_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="student_management_app.staff",
                    ),
                ),
            ],
        ),
    ]
