# Generated by Django 5.1 on 2024-08-23 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student_management_app", "0010_alter_staffleave_leave_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployeeLeave",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("from_date", models.CharField(max_length=50)),
                ("to_date", models.CharField(max_length=50)),
                ("messages", models.TextField()),
                (
                    "leave_type",
                    models.CharField(
                        choices=[("full day", "Full Day"), ("half day", "Half Day")],
                        default="full day",
                        max_length=20,
                    ),
                ),
                ("status", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "employee_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="student_management_app.employee",
                    ),
                ),
            ],
        ),
    ]
