# Generated by Django 5.1 on 2024-08-29 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student_management_app", "0011_employeeleave"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="full_day_leaves_remaining",
            field=models.IntegerField(default=12),
        ),
        migrations.AddField(
            model_name="employee",
            name="half_day_leaves_remaining",
            field=models.IntegerField(default=6),
        ),
        migrations.AddField(
            model_name="staff",
            name="full_day_leaves_remaining",
            field=models.IntegerField(default=12),
        ),
        migrations.AddField(
            model_name="staff",
            name="half_day_leaves_remaining",
            field=models.IntegerField(default=6),
        ),
    ]
