# Generated by Django 4.2.2 on 2024-09-14 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0012_employee_full_day_leaves_remaining_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='half_day_leaves_remaining',
            field=models.IntegerField(default=12),
        ),
        migrations.AlterField(
            model_name='staff',
            name='half_day_leaves_remaining',
            field=models.IntegerField(default=12),
        ),
    ]
