# Generated by Django 4.2.2 on 2024-09-14 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0013_alter_employee_half_day_leaves_remaining_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='father_occupation',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='mother_occupation',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='father_occupation',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='mother_occupation',
        ),
    ]
